name: Echo  

on:
  pull_request:
    branches:
      - '2.x'
      - 'main'
      - '!releases/*'
      
  workflow_dispatch: 

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
          with:
            fetch-depth: 0
            ref: ${{ github.base_ref }}

      - run: git log
          

