# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "2.x" ]
    branches-ignore:
      - 'releases/*'

  pull_request:
    branches: [ "2.x" ]
    branches-ignore:
      - 'releases/*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install

    - name: Bootstrap monorepo
      run: npm run bootstrap:monorepo

    - name: Lint packages
      run: npm run lint

    - name: Build packages
      run: npm run build

    # - name: Test packages
    #   run: npm run test
