name: Versioning

on:
  pull_request:
    branches: 
      - '2.x'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
        ref: ${{ github.base_ref }}

    - run: git pull

    - name: Set up git user
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        git config advice.addIgnoredFile false
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
          
    - run: npm ci

    - name: Tag Version
      run: |
        npm run new-version

    - name: Get name & version from package.json
      shell: bash
      run: echo "##[set-output name=version;]$(node -p -e '`${require("./lerna.json").version}`')"
      id: package_json

    - name: Set the value
      run: echo "pkg_version=${{ steps.package_json.outputs.version }}" >> $GITHUB_ENV

    - name: Push version file changes
      uses: ad-m/github-push-action@master
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        branch: 'release/${{ env.pkg_version }}'

    - name: Checkout Release
      uses: actions/checkout@master
      with:
        fetch-depth: 0
        ref: release/${{ env.pkg_version }}

    - name: Create Pull Request to Main
      uses: peter-evans/create-pull-request@v4
      with:
        base: main
        branch: release/${{ env.pkg_version }}

    - name: Create Pull Request to Develop
      uses: peter-evans/create-pull-request@v4
      with:
        base: ${{ github.ref }}
        branch: release/${{ env.pkg_version }}
